### PR TITLE
Ensure peer arg ordering is correct 

### LINKED ISSUE #11: Debug VPN connection
**Describe the bug**
Issues connecting to the wireguard network.

**To Reproduce**
1. Place `wg_config.conf` file in `priv/` directory of app
2. `ssh nerves.local`
3. `wg_conf = Application.app_dir(:my_app) |> Path.join("priv/wg_config.conf") |> VintageNetWireguard.ConfigFile.parse`
4. `VintageNet.configure("wg0", wg_conf)`
5. `ifconfig`, shows status of `wg0: flags=[:up, :pointtopoint, :running] inet 192.168.178.202  netmask 255.255.255.0`
6. `ping("1.1.1.1", ifname: "wg0")` - results in `:eaddrnotavail`

**Expected behavior**
The goal is to expose a service over the wireguard network, so I would anticipate that `ping` should work

**VintageNet Info**

```
VintageNet 0.13.4

All interfaces:       ["can0", "eth0", "lo", "wg0", "wlan0"]
Available interfaces: ["wlan0"]

Interface wg0
  Type: VintageNetWireguard
  Present: true
  State: :retrying (24.6 s)
  Connection: :disconnected (0:01:43)
  Addresses: 192.168.178.202/24
  MAC Address: nil
  Configuration:
    %{
      type: VintageNetWireguard,
      dns: [{192, 168, 178, 1}],
      addresses: [{{192, 168, 178, 202}, 24}],
      private_key: "....",
      peers: [
        %{
          public_key: "redacted",
          preshared_key: "....",
          persistent_keepalive: 25,
          endpoint: "redacted",
          allowed_ips: [{{192, 168, 178, 0}, 24}, {{0, 0, 0, 0}, 0}]
        }
      ]
    }

Interface wlan0
  Type: VintageNetWiFi
  Present: true
  State: :configured (0:01:43)
  Connection: :internet (0:01:36)
  Addresses: 192.168.178.33/24, redacted/64, redacted/64
  MAC Address: "b8:27:eb:3a:ea:1f"
  Configuration:
    %{
      type: VintageNetWiFi,
      vintage_net_wifi: %{
        networks: [
          %{mode: :infrastructure, psk: "....", ssid: "myssid", key_mgmt: :wpa_psk}
        ]
      },
      ipv4: %{method: :dhcp}
    }
```

**Environment**

```
 Pkg:         custom_rpi3 - this is the same as the most recent release of nerves_system_rpi3
  Vsn:         1.23.1
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, [make_args: ["source", "all", "legal-info"]]}

  Pkg:         nerves_toolchain_armv7_nerves_linux_gnueabihf
  Vsn:         1.8.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.9.3
  Type:        toolchain_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_system_br
  Vsn:         1.23.2
  Type:        system_platform
  BuildRunner: {nil, []}
```

**Additional context**
Running on Raspberry Pi 3. The VintageNet configuration shown above is for connecting to my home network VPN (Fritz!Box Wireguard), however since I don't trust that I configured everything correctly or that it would work when connecting to the VPN server running on the local network, I also tried connecting to `fly.io` via the `fly fireguard create` command and using the output config file in the same manner as above, with the same `:disconnected` result. 

I also tried changing the `DNS` key in the `.conf` file to a public DNS (`1.1.1.1`), but that didn't change the result either.

I know that writing docs for connecting to Fly.io is on the to-do list, so if I figure this out I'd be happy to help with that! 

Thank you :)

### PR DESCRIPTION
**Pull request by jjcarstens**
Fixes #11

With OTP 26, map orderings were slightly changed. This made one of the arguments
become out of order when setting a peer up with `wg`.

This change enforces that expected order now

Also adds a few cleanup commits:
* Print stderr_to_stdout with wg commands
* Scope logger messages to module

### CODE REVIEW

File: lib/vintage_net_wireguard.ex [hunk 1]
```diff
@@ -240,7 +240,8 @@ defmodule VintageNetWireguard do
 
   defp set_peer(ifname, peer) do
     with {:ok, tracker} <- Temp.track(),
-         peer_args = Enum.reduce(peer, [], &add_peer_arg/2),
+         # peer arg needs to be first
+         peer_args = ["peer", peer.public_key | Enum.reduce(peer, [], &add_peer_arg/2)],
```
Comment (fhunleth) [inline lib/vintage_net_wireguard.ex:247]: Wow, I was expecting the standard solution to this which is to call `Enum.sort/1` first to get the old ordering back. I was wondering how `"peer"` was guaranteed first in OTP 25 and earlier. It looks like `:public_key` is the last one alphabetically and the args are in reverse order. That's kind of sneaky!

File: lib/vintage_net_wireguard.ex [hunk 2]
```diff
@@ -195,7 +195,7 @@ defmodule VintageNetWireguard do
   end
 
   defp maybe_add_interface(ifname) do
-    case System.cmd("ip", ["link", "show", ifname]) do
+    case System.cmd("ip", ["link", "show", ifname], stderr_to_stdout: true) do
```
Comment (fhunleth) [inline lib/vintage_net_wireguard.ex:201]: Output is ignored here, so this would cause stderr messages to be hidden if you're watching stderr on a serial console. I'm not sure I'd want this, but I also don't believe `ip` would give anything super helpful either.

File: lib/vintage_net_wireguard.ex (hunk 1 above)
Comment (jjcarstens) [reply lib/vintage_net_wireguard.ex:247]: Very sneaky. I opted this way over `Enum.sort` in case we ever add more options and we don't have to think about the sneaky bug again
